window.translations = [
  {
    id: 52,
    local_title: "Dios Habla Hoy",
    audio: false,
    local_abbreviation: "DHH94I"
  },
  {
    id: 89,
    local_title: "La Biblia de Las Américas",
    audio: false,
    local_abbreviation: "LBLA"
  },
  {
    id: 103,
    local_title: "Nueva Biblia de Las Américas",
    audio: false,
    local_abbreviation: "NBLA"
  },
  {
    id: 127,
    local_title: "Nueva Traducción Viviente",
    audio: true,
    local_abbreviation: "NTV"
  },
  {
    id: 128,
    local_title: "Nueva Versión Internacional",
    audio: false,
    local_abbreviation: "NVI"
  },
  {
    id: 197,
    local_title: "Palabra de Dios para Todos",
    audio: false,
    local_abbreviation: "PDT"
  },
  {
    id: 149,
    local_title: "Reina Valera 1960",
    audio: false,
    local_abbreviation: "RVR1960"
  },
  {
    id: 1782,
    local_title: "Reina Valera Actualizada",
    audio: false,
    local_abbreviation: "RVA2015"
  },
  {
    id: 176,
    local_title: "Traducción en Lenguaje Actual",
    audio: false,
    local_abbreviation: "TLA"
  },
];
window.books = [
  { human: "Génesis", usfm: "GEN", chapters: 50 },
  { human: "Éxodo", usfm: "EXO", chapters: 40 },
  { human: "Levítico", usfm: "LEV", chapters: 27 },
  { human: "Numeros", usfm: "NUM", chapters: 36 },
  { human: "Deuteronomio", usfm: "DEU", chapters: 34 },
  { human: "Josué", usfm: "JOS", chapters: 24 },
  { human: "Jueces", usfm: "JDG", chapters: 21 },
  { human: "Ruth", usfm: "RUT", chapters: 4 },
  { human: "1 Samuel", usfm: "1SA", chapters: 31 },
  { human: "2 Samuel", usfm: "2SA", chapters: 24 },
  { human: "1 Reyes", usfm: "1KI", chapters: 22 },
  { human: "2 Reyes", usfm: "2KI", chapters: 25 },
  { human: "1 Crónicas", usfm: "1CH", chapters: 29 },
  { human: "2 Crónicas", usfm: "2CH", chapters: 36 },
  { human: "Esdras", usfm: "EZR", chapters: 10 },
  { human: "Nehemías", usfm: "NEH", chapters: 13 },
  { human: "Ester", usfm: "EST", chapters: 10 },
  { human: "Job", usfm: "JOB", chapters: 42 },
  { human: "Salmos", usfm: "PSA", chapters: 150 },
  { human: "Proverbios", usfm: "PRO", chapters: 31 },
  { human: "Eclesiastés", usfm: "ECC", chapters: 12 },
  { human: "Cantar de los Cantares", usfm: "SNG", chapters: 8 },
  { human: "Isaías", usfm: "ISA", chapters: 66 },
  { human: "Jeremías", usfm: "JER", chapters: 52 },
  { human: "Lamentaciones", usfm: "LAM", chapters: 5 },
  { human: "Ezequiel", usfm: "EZK", chapters: 48 },
  { human: "Daniel", usfm: "DAN", chapters: 12 },
  { human: "Oseas", usfm: "HOS", chapters: 14 },
  { human: "Joel", usfm: "JOL", chapters: 3 },
  { human: "Amós", usfm: "AMO", chapters: 9 },
  { human: "Abdías", usfm: "OBA", chapters: 1 },
  { human: "Jonás", usfm: "JON", chapters: 4 },
  { human: "Miqueas", usfm: "MIC", chapters: 7 },
  { human: "Nahúm", usfm: "NAM", chapters: 3 },
  { human: "Habacuc", usfm: "HAB", chapters: 3 },
  { human: "Sofonía", usfm: "ZEP", chapters: 3 },
  { human: "Hageo", usfm: "HAG", chapters: 2 },
  { human: "Zacarías", usfm: "ZEC", chapters: 14 },
  { human: "Malaquías", usfm: "MAL", chapters: 4 },
  { human: "Mateo", usfm: "MAT", chapters: 28 },
  { human: "Marcos", usfm: "MRK", chapters: 16 },
  { human: "Lucas", usfm: "LUK", chapters: 24 },
  { human: "Juan", usfm: "JHN", chapters: 21 },
  { human: "Hechos", usfm: "ACT", chapters: 28 },
  { human: "Romanos", usfm: "ROM", chapters: 16 },
  { human: "1 Corintios", usfm: "1CO", chapters: 16 },
  { human: "2 Corintios", usfm: "2CO", chapters: 13 },
  { human: "Gálatas", usfm: "GAL", chapters: 6 },
  { human: "Efesios", usfm: "EPH", chapters: 6 },
  { human: "Filipenses", usfm: "PHP", chapters: 4 },
  { human: "Colosenses", usfm: "COL", chapters: 4 },
  { human: "1 Tesalonicenses", usfm: "1TH", chapters: 5 },
  { human: "2 Tesalonicenses", usfm: "2TH", chapters: 3 },
  { human: "1 Timoteo", usfm: "1TI", chapters: 6 },
  { human: "2 Timoteo", usfm: "2TI", chapters: 4 },
  { human: "Tito", usfm: "TIT", chapters: 3 },
  { human: "Filemón", usfm: "PHM", chapters: 1 },
  { human: "Hebreos", usfm: "HEB", chapters: 13 },
  { human: "Santiago", usfm: "JAS", chapters: 5 },
  { human: "1 Pedro", usfm: "1PE", chapters: 5 },
  { human: "2 Pedro", usfm: "2PE", chapters: 3 },
  { human: "1 Juan", usfm: "1JN", chapters: 5 },
  { human: "2 Juan", usfm: "2JN", chapters: 1 },
  { human: "3 Juan", usfm: "3JN", chapters: 1 },
  { human: "Judas", usfm: "JUD", chapters: 1 },
  { human: "Apocalípsis", usfm: "REV", chapters: 22 }
];
